serializer: LEGACY

# Координаты блоков-подарков в формате "world:x:y:z"
gifts:
  locations:
    - "world:100:64:200"
    - "world:150:64:250"
    - "world:200:64:300"


# Команды, которые выполняются при получении награды
# Используйте %sender% для замены на имя игрока
command-on-complete:
  - "give %sender% diamond 10"
  - "say %sender% получил награду за все подарки!"
  # Добавьте больше команд по необходимости

# Сообщения
messages:
  gift-collected: "&aВы забрали 1 подарок!"
  gift-already-collected: "&cВы уже собрали этот подарок!"
  reward-success: "&aМолодец! Ты выполнил все задания!"
  not-all-gifts: "&cВы собрали не все подарки! Собрано: %collected%/%total%"
  already-claimed: "&cВы уже получили награду!"